- name: Download cfssl
  get_url:
    url: "{{cfssl_addr}}/cfssl_linux-amd64"
    dest: /usr/local/bin/cfssl
    mode: 0755
    
- name: Download cfssljson
  get_url:
    url: "{{cfssl_addr}}/cfssljson_linux-amd64"
    dest: /usr/local/bin/cfssljson
    mode: 0755

- name: Download cfssl-certinfo
  get_url:
    url: "{{cfssl_addr}}/cfssl-certinfo_linux-amd64"
    dest: /usr/local/bin/cfssl-certinfo
    mode: 0755
